{% set name = "rotary-embedding-torch" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0c608f180d27619dd7647276de981959586fccd45cbfd6d2ed2f0174d897c658

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - beartype
    - einops >=0.7
    - pytorch >=2.0

test:
  imports:
    - rotary_embedding_torch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/rotary-embedding-torch
  summary: Rotary Embedding - Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leightonpayne
