{% set name = "rotary-embedding-torch" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rotary-embedding-torch-{{ version }}.tar.gz
  sha256: 45db29b19bd7025f09d202752c26bf6921b05d8b5a977cfcdc625ce96ddf2b5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beartype
    - einops >=0.7
    - pytorch >=2.0

test:
  imports:
    - rotary_embedding_torch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/rotary-embedding-torch
  summary: Rotary Embedding - Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leightonpayne
