schema_version: 1

context:
  name: rotary-embedding-torch
  version: 0.8.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 42cdb6d997356f0f026f0b6fd7f0af84b846b84bc0353826153ad67259e244b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - einops >=0.7
    - pytorch >=2.0

tests:
  - python:
      imports:
        - rotary_embedding_torch
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Rotary Embedding - Pytorch
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lucidrains/rotary-embedding-torch

extra:
  recipe-maintainers:
    - leightonpayne
    - synapticarbors
